### ISSUE TITLE
HTML homepage template variables not filled properly

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#68] opened 2024-03-23 10:09 UTC
To reproduce the following screenshot, just click on top left « home » logo:
<img width="1024" alt="image" src="https://github.com/openzim/nautilus/assets/1029718/c49975cb-ac14-4e0d-abeb-0306d04c45dd">

I expect search boxes (ZIM) are « ugly »

**Comment by rgaudin** [comment] 2024-03-23 10:18
I believe the expectation is met then 😂

**Comment by rgaudin** [comment] 2024-03-23 17:31
The link points to `home.html` instead of `home`. That's the issue.

**Comment by rgaudin** [comment] 2024-03-23 17:34
Duplicate of #66

**Closed** 2024-03-26 14:22 UTC
Labels: bug, good first issue
