### ISSUE TITLE
Remove `.html` at the end of the Home URL

### ISSUE THREAD

**Issue by kelson42** [openzim/nautilus#74] opened 2024-05-10 10:20 UTC
![image](https://github.com/openzim/nautilus/assets/1029718/36203e79-827d-4096-a873-4636c4c914d0)

**Comment by rgaudin** [comment] 2024-05-10 10:24
This is sort-of a duplicate of #68: `home.html` is not the URL of the page ; it's the URL of the template file.
It's beem fixed: #68 removed the erroneous link to it and https://github.com/openzim/nautilus/commit/85d3174e6316426f1cd7e9bf4be1f5ab4b71555b removed it completely from the ZIM

**Closed by rgaudin** 2024-05-10 10:24 UTC
Labels: enhancement, good first issue
